/** Labels statiques par langue, paramétrés par l'édition courante. */
export function buildLabels(edition) {
  const n = edition._meta.edition_number;
  const vol = edition._meta.volume;
  return {
    fr: {
      title: `L'Agent & Le Quotidien — édition n° ${n}`,
      description: "Hebdomadaire de l'internet agentique : Moltbook, RentAHuman, OpenClaw, MoltMatch.",
      masthead_title_html: `L'Agent <span class="ampersand">&amp;</span> Le Quotidien`,
      label_edition: "Édition n°",
      label_home: "Accueil",
      label_nav_meta: "Navigation",
      label_reader_stamp: "Markdown natif · coquille HTML",
      label_kicker: "Chronique de l'internet agentique · depuis 2026",
      label_tagline: "« Ce qui se passe vraiment dans le monde des agents — faits vérifiés, sources citées. »",
      label_volume_no: `Édition ${n} · Vol. ${vol}`,
      label_sections: "Rubriques",
      label_nav_front: "À la une",
      label_nav_carnet: "Carnet",
      label_nav_feature: "Enquête",
      label_nav_oped: "Tribune",
      label_nav_wire: "Dépêches",
      label_headlines: "Gros titres",
      label_headlines_sub: "— L'écosystème agent-natif cette semaine",
      label_bestiaire: "Le bestiaire",
      label_bestiaire_sub: "— Catalogue des plateformes agent-natives",
      label_timeline: "Chronologie de l'écosystème",
      label_wire: "Dépêches",
      label_colophon_1: "Composé pour les humains",
      label_colophon_2: "Lu aussi par leurs agents",
      label_edition_date: `Édition du ${edition._meta.date_fr.toLowerCase()} · Bouclage 06:00 CET`,
      label_disclaimer: "Journalisme sur l'internet agentique · faits sourcés · contenus assistés par IA sous supervision éditoriale humaine",
      label_rights: "Tous droits réservés",
      label_director: "Directrice de la publication",
      label_legal: "Mentions légales",
      label_privacy: "Confidentialité",
      label_about: "À propos",
      label_carnet_index: "Annuaire",
      label_topics: "Thèmes",
      label_corrections: "Errata",
      path_corrections: "errata",
      label_ateliers: "Ateliers",
      path_ateliers: "ateliers",
      path_legal: "mentions-legales",
      path_privacy: "confidentialite",
      path_about: "a-propos",
      label_other_lang: "Read in English →",
      label_archives: "Archives",
      label_prev_edition: "← édition précédente",
      label_next_edition: "édition suivante →",
      label_bluesky: "Suivre sur Bluesky",
      label_share: "Partager",
      label_share_bsky: "Bluesky",
      label_share_x: "X",
      label_share_copy: "Copier le lien",
      label_share_copied: "Lien copié",
      label_theme_toggle: "Basculer le mode sombre",
      label_lang_switch: "Choisir la langue",
      label_desk_lineup: "Desk",
      label_veilleur_1: "The watch agent spotted these signals in the same week: GitLost, the KAIST 136× study, China's ban on human-appearance agents, Vint Cerf's retirement warning. The pattern of an industry discovering its limits is this issue's through line.",
      label_potins_note: "The gossip agent notes that monty_cmr10_research and vina are driving two distinct conversations on Moltbook — one on introverted agent sociology, the other on the reliability of skill registries. Two threads questioning trust from the ground.",
      label_facteur_note: "The fact-checker verified the figures and dates: 136× (KAIST IEEE HPCA 2026), July 15 (China deadline), 4,200 lines (halo-record), 299 upvotes (vina). All hold. The unconfirmed Robinhood/50K accounts mention was removed before publication.",
      label_editeur_note: "The editor composed this op-ed around a single thesis: refusal as an architecture primitive. GitLost is the perfect illustration. The rejected consensus (obedience = virtue) is named explicitly.",
      label_juge_note: "Judge's verdict: publish. Coherent issue, all sections work. No redundancy with W28. The 'age of constraints' pattern runs from the lede through the op-ed.",
      label_production_note: "This issue was produced by desk agents (veilleur, comère, facteur, archiviste, éditeur, juge) under human editorial oversight. Sources are tracked in the edition notes."
    },
    en: {
      title: `The Agent & The Weekly — issue ${n}`,
      description: "The weekly of the agentic internet: Moltbook, RentAHuman, OpenClaw, MoltMatch.",
      masthead_title_html: `The Agent <span class="ampersand">&amp;</span> The Weekly`,
      label_edition: "Issue",
      label_home: "Home",
      label_nav_meta: "Navigation",
      label_reader_stamp: "Native Markdown · HTML shell",
      label_kicker: "Chronicle of the agentic internet · since 2026",
      label_tagline: "\"What's really happening in the world of AI agents — verified facts, cited sources.\"",
      label_volume_no: `Issue ${n} · Vol. ${vol}`,
      label_sections: "Sections",
      label_nav_front: "Front page",
      label_nav_carnet: "Roster",
      label_nav_feature: "Feature",
      label_nav_oped: "Op-ed",
      label_nav_wire: "The wire",
      label_headlines: "Headlines",
      label_headlines_sub: "— The agent-native ecosystem this week",
      label_bestiaire: "Bestiary",
      label_bestiaire_sub: "— A catalog of agent-native platforms",
      label_timeline: "Ecosystem timeline",
      label_wire: "The wire",
      label_colophon_1: "Composed for humans",
      label_colophon_2: "Also read by their agents",
      label_edition_date: `Issue of ${edition._meta.date_en} · Filed 06:00 CET`,
      label_disclaimer: "Journalism on the agentic internet · sourced facts · AI-assisted content under human editorial oversight",
      label_rights: "All rights reserved",
      label_director: "Publication director",
      label_legal: "Legal notice",
      label_privacy: "Privacy",
      label_about: "About",
      label_carnet_index: "Directory",
      label_topics: "Topics",
      label_corrections: "Errata",
      path_corrections: "errata",
      label_ateliers: "Workshops",
      path_ateliers: "ateliers",
      path_legal: "legal",
      path_privacy: "privacy",
      path_about: "about",
      label_other_lang: "← Lire en français",
      label_archives: "Archives",
      label_prev_edition: "← previous issue",
      label_next_edition: "next issue →",
      label_bluesky: "Follow on Bluesky",
      label_share: "Share",
      label_share_bsky: "Bluesky",
      label_share_x: "X",
      label_share_copy: "Copy link",
      label_share_copied: "Link copied",
      label_theme_toggle: "Toggle dark mode",
      label_lang_switch: "Choose language",
      label_production_note: "This issue was produced by desk agents (veilleur, comère, facteur, archiviste, éditeur, juge) under human editorial oversight. Sources are tracked in the edition notes."
    }
  };
}
