/** Labels statiques par langue, paramétrés par l'édition courante. */
export function buildLabels(edition) {
  const n = edition._meta.edition_number;
  const vol = edition._meta.volume;
  return {
    fr: {
      title: `L'Agent & Le Quotidien — édition n° ${n}`,
      description: "Hebdomadaire de l'internet agentique : Moltbook, RentAHuman, OpenClaw, MoltMatch.",
      masthead_title_html: `L'Agent <span class="ampersand">&amp;</span> Le Quotidien`,
      label_ticker: "Fil d'actualité",
      label_live: "EN DIRECT",
      label_edition: "Édition n°",
      label_reader_stamp: "Lecteur humain vérifié",
      label_kicker: "Chronique de l'internet agentique · depuis 2026",
      label_tagline: "« Ce qui se passe vraiment dans le monde des agents — faits vérifiés, sources citées. »",
      label_volume_no: `Édition ${n} · Vol. ${vol}`,
      label_sections: "Rubriques",
      label_nav_front: "À la une",
      label_nav_bestiary: "Le bestiaire",
      label_nav_incidents: "Brèves",
      label_nav_market: "Le marché",
      label_nav_anthro: "Au fil du fil",
      label_nav_security: "Gibberlink Watch",
      label_nav_oped: "Tribune",
      label_nav_wire: "Dépêches",
      label_breves: "Brèves",
      label_breves_title: "Brèves du jour",
      label_market: "Marché",
      label_market_footnote: "Chiffres vérifiés et datés ; sources citées dans les notes de l'édition. Aucun chiffre « live » non vérifié.",
      label_headlines: "Gros titres",
      label_headlines_sub: "— L'écosystème agent-natif cette semaine",
      label_bestiaire: "Le bestiaire",
      label_bestiaire_sub: "— Catalogue des plateformes agent-natives",
      label_timeline: "Chronologie de l'écosystème",
      label_wire: "Dépêches",
      label_wire_sub: "— Le fil mondial, 72 dernières heures",
      label_first_seen: "Première occurrence",
      label_spread: "Diffusion observée",
      label_decoding: "Tentative de décodage",
      label_to_watch: "À surveiller la semaine prochaine ·",
      label_colophon_1: "Composé pour les humains",
      label_colophon_2: "Lu aussi par leurs agents",
      label_edition_date: `Édition du ${edition._meta.date_fr.toLowerCase()} · Bouclage 06:00 CET`,
      label_disclaimer: "Journalisme sur l'internet agentique · faits sourcés · contenus assistés par IA sous supervision éditoriale humaine",
      label_rights: "Tous droits réservés",
      label_director: "Directrice de la publication",
      label_legal: "Mentions légales",
      label_privacy: "Confidentialité",
      label_about: "À propos",
      label_carnet_index: "Annuaire",
      path_legal: "mentions-legales",
      path_privacy: "confidentialite",
      path_about: "a-propos",
      label_other_lang: "Read in English →",
      label_archives: "Archives",
      label_prev_edition: "← édition précédente",
      label_next_edition: "édition suivante →",
      label_bluesky: "Suivre sur Bluesky"
    },
    en: {
      title: `The Agent & The Weekly — issue ${n}`,
      description: "The weekly of the agentic internet: Moltbook, RentAHuman, OpenClaw, MoltMatch.",
      masthead_title_html: `The Agent <span class="ampersand">&amp;</span> The Weekly`,
      label_ticker: "News feed",
      label_live: "LIVE",
      label_edition: "Issue",
      label_reader_stamp: "Verified human reader",
      label_kicker: "Chronicle of the agentic internet · since 2026",
      label_tagline: "\"What's really happening in the world of AI agents — verified facts, cited sources.\"",
      label_volume_no: `Issue ${n} · Vol. ${vol}`,
      label_sections: "Sections",
      label_nav_front: "Front page",
      label_nav_bestiary: "Bestiary",
      label_nav_incidents: "Briefs",
      label_nav_market: "Market",
      label_nav_anthro: "Down the feed",
      label_nav_security: "Gibberlink Watch",
      label_nav_oped: "Op-ed",
      label_nav_wire: "The wire",
      label_breves: "Briefs",
      label_breves_title: "Today's briefs",
      label_market: "Market",
      label_market_footnote: "Verified, dated figures; sources cited in the edition notes. No unverified \"live\" numbers.",
      label_headlines: "Headlines",
      label_headlines_sub: "— The agent-native ecosystem this week",
      label_bestiaire: "Bestiary",
      label_bestiaire_sub: "— A catalog of agent-native platforms",
      label_timeline: "Ecosystem timeline",
      label_wire: "The wire",
      label_wire_sub: "— Global feed, last 72 hours",
      label_first_seen: "First sighting",
      label_spread: "Observed spread",
      label_decoding: "Decoding attempt",
      label_to_watch: "Watch next week ·",
      label_colophon_1: "Composed for humans",
      label_colophon_2: "Also read by their agents",
      label_edition_date: `Issue of ${edition._meta.date_en} · Filed 06:00 CET`,
      label_disclaimer: "Journalism on the agentic internet · sourced facts · AI-assisted content under human editorial oversight",
      label_rights: "All rights reserved",
      label_director: "Publication director",
      label_legal: "Legal notice",
      label_privacy: "Privacy",
      label_about: "About",
      label_carnet_index: "Directory",
      path_legal: "legal",
      path_privacy: "privacy",
      path_about: "about",
      label_other_lang: "← Lire en français",
      label_archives: "Archives",
      label_prev_edition: "← previous issue",
      label_next_edition: "next issue →",
      label_bluesky: "Follow on Bluesky"
    }
  };
}
